# Generated by Django 5.2.15 on 2026-06-08 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_skyhook_monitor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skyhook",
            name="structure_name",
        ),
        migrations.AddField(
            model_name="skyhook",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="SkyhookReagent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_id", models.IntegerField()),
                ("type_name", models.CharField(blank=True, max_length=255)),
                ("secured_stock", models.BigIntegerField(default=0)),
                ("unsecured_stock", models.BigIntegerField(default=0)),
                (
                    "skyhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reagents",
                        to="aa_skyhook_monitor.skyhook",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("skyhook", "type_id")},
            },
        ),
        migrations.DeleteModel(
            name="SkyhookBayItem",
        ),
    ]
