# Generated by Django 5.2.15 on 2026-06-08 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aa_skyhook_monitor", "0004_skyhookreagent_volume"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skyhookowner",
            options={
                "default_permissions": (),
                "permissions": (
                    ("view_skyhooks", "Can view Skyhook bay contents"),
                    ("manage_skyhooks", "Can add and remove corporations"),
                ),
            },
        ),
    ]
