# Generated by Django 5.2.15 on 2026-06-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_skyhook_monitor', '0008_alter_skyhookconfiguration_discord_webhook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skyhookconfiguration',
            name='last_full_sync',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last full ESI sync run', null=True),
        ),
    ]
