# Generated by Django 5.2.15 on 2026-06-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_skyhook_monitor", "0009_skyhookconfiguration_last_full_sync"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaidableSkyhook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planet_id", models.IntegerField()),
                ("solar_system_id", models.IntegerField(db_index=True)),
                ("solar_system_name", models.CharField(max_length=100)),
                ("security_status", models.FloatField(default=0)),
                ("constellation_name", models.CharField(max_length=100)),
                ("region_name", models.CharField(max_length=100)),
                ("theft_vulnerability_start", models.DateTimeField()),
                ("theft_vulnerability_end", models.DateTimeField()),
            ],
            options={
                "ordering": ["theft_vulnerability_start"],
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="skyhook",
            name="effective_workforce",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="skyhook",
            name="reinforcement_timer_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="skyhookconfiguration",
            name="last_raidable_sync",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last raidable-skyhooks fetch",
                null=True,
            ),
        ),
    ]
