# Generated by Django 5.2.15 on 2026-06-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_skyhook_monitor", "0010_raidable_skyhook_and_detail_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaidWatchConstellation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("region_name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["region_name", "name"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="RaidWatchRegion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="skyhookconfiguration",
            name="watched_constellations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Show only raidable skyhooks in these constellations (empty = show all).",
                related_name="+",
                to="aa_skyhook_monitor.raidwatchconstellation",
            ),
        ),
        migrations.AddField(
            model_name="skyhookconfiguration",
            name="watched_regions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Show only raidable skyhooks in these regions (empty = show all).",
                related_name="+",
                to="aa_skyhook_monitor.raidwatchregion",
            ),
        ),
    ]
