# Generated by Django 5.2.15 on 2026-06-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_skyhook_monitor", "0011_raid_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="raidableskyhook",
            name="planet_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
