# Generated by Django 5.2.15 on 2026-06-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_skyhook_monitor", "0012_raidableskyhook_planet_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="skyhookconfiguration",
            name="raidable_webhook_url",
            field=models.URLField(
                blank=True,
                help_text="Discord webhook URL for raidable-skyhook alerts (empty = disabled)",
            ),
        ),
        migrations.AlterField(
            model_name="skyhookconfiguration",
            name="discord_webhook_url",
            field=models.URLField(
                blank=True,
                help_text="Discord webhook URL for own-skyhook notifications (empty = disabled)",
            ),
        ),
        migrations.CreateModel(
            name="RaidableNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planet_id", models.IntegerField()),
                ("solar_system_id", models.IntegerField()),
                ("theft_vulnerability_start", models.DateTimeField()),
                ("theft_vulnerability_end", models.DateTimeField()),
                ("notified_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("planet_id", "theft_vulnerability_start")},
            },
        ),
    ]
