# Generated by Django 5.2.15 on 2026-06-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "aa_skyhook_monitor",
            "0013_skyhookconfiguration_raidable_webhook_url_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skyhook",
            name="effective_workforce",
        ),
        migrations.RemoveField(
            model_name="skyhook",
            name="reinforcement_timer_end",
        ),
    ]
