# Generated by Django 5.2.15 on 2026-06-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_skyhook_monitor", "0014_remove_skyhook_effective_workforce_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RaidableNotification",
        ),
        migrations.AddField(
            model_name="raidableskyhook",
            name="notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="raidableskyhook",
            unique_together={("planet_id", "theft_vulnerability_start")},
        ),
    ]
